import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "JJ E13492",
    name: "Silver Black Full Rim Supreme Steel JJ E13492-C2",
    brand: "JOHNJACOBS",
    price: "4000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648149786/House%20Of%20Glass/Products/Silver-Black-Full-Rim-Round-John-Jacobs-Supreme-Steel-JJ-E13492-C2-Eyeglasses_john-jacobs-jj-e13492-c2-eyeglasses_G_8232_10_02_2022-removebg-preview_vyg30e.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.2,
    count: 0,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "JJ E11473",
    name: "Black Full Rim Round Eyeglasses",
    price: "4000",
    brand: "JOHNJACOBS",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150058/House%20Of%20Glass/Products/john-jacobs-jj-e11473-c1-eyeglasses_john-jacobs-jj-e11473-c1-eyeglasses_john-jacobs-jj-e11473-c1-eyeglasses_g_0143_1-removebg-preview_lifc2w.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 3.9,
    count: 0,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "og-sweathsirt",
    name: "OG Sweatshirt",
    price: "9499",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/OGJacket_m6aett.webp",
    fastDelivery: false,
    discount: "11",
    rating: 3.9,
    count: 0,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "razer-eyboard",
    name: "Razer Keyboard",
    price: "4999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647683341/AegisStore/products/keyboards/RazerKeyboard_kwqldy.webp",
    fastDelivery: false,
    discount: "20",
    rating: 2.5,
    count: 10,
    categoryName: "keyboard",
  },
  {
    _id: uuid(),
    title: "astralis-hoodie",
    name: "Astralis Hoodie",
    price: "9499",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/Astralis_h9wuju.webp",
    fastDelivery: false,
    discount: "21",
    rating: 2.9,
    count: 4,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "FOS 7108",
    name: "Matte Grey Transparent Full Rim Round Eyeglasses",
    brand: "VOGUE",
    price: "7400",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150578/House%20Of%20Glass/Products/fossil-fos-7108-63m-eyeglasses_G_6613-removebg-preview_phw0dr.png",
    fastDelivery: true,
    discount: 0.6,
    rating: 4.9,
    count: 20,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "logitech-eyboard",
    name: "Logitech Keyboard",
    price: "2999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647683341/AegisStore/products/keyboards/LogitechKeyboard_jf946c.webp",
    fastDelivery: false,
    discount: "21",
    rating: 4.3,
    count: 50,
    categoryName: "keyboard",
  },
  {
    _id: uuid(),
    title: "team-liquid-hoodie",
    name: "Team Liquid Hoodie",
    price: "10999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647750565/AegisStore/products/hoodies/TeamLiquidHoodie_xf39pk.webp",
    fastDelivery: true,
    discount: "21",
    rating: 4.5,
    count: 31,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "hyper-x-keyboard",
    name: "HyperX Keyboard",
    price: "4499",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647683341/AegisStore/products/keyboards/HyperXKeyboard_telwpp.webp",
    fastDelivery: TrustedTypePolicyFactory,
    discount: "11",
    rating: 4.0,
    count: 20,
    categoryName: "keyboard",
  },
  {
    _id: uuid(),
    title: "secret-lab-chair",
    name: "Secret Lab Chair",
    price: "15999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682690/AegisStore/products/chairs/SecretLabChair_viuvv1.webp",
    fastDelivery: true,
    discount: "41",
    rating: 4.6,
    count: 11,
    categoryName: "chair",
  },
  {
    _id: uuid(),
    title: "VC E12707",
    name: "Grey Silver Full Rim Round Eyeglasses",
    brand: "VINCENT CHASE",
    price: "999",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150953/House%20Of%20Glass/Products/vincent-chase-vc-e12707-foll-rim-rnd-tr90ss-mtl-c5-eyegasus_g_9058-removebg-preview_ju7nnc.png",
    fastDelivery: false,
    discount: 0,
    rating: 4.5,
    count: 20,
    categoryName: "round",
  },
  {
    _id: uuid(),
    title: "nigma-galaxy-hoodie",
    name: "Nigma Galaxy Hoodie",
    price: "9299",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/NigmaHoodie_d26irz.webp",
    fastDelivery: false,
    discount: "10",
    rating: 4.1,
    count: 20,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "JJ E12629",
    name: "Pro Titanium Silver Rimless Round Eyeglasses",
    brand: "JOHNJACOBS",
    price: "5000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648151070/House%20Of%20Glass/Products/john-jacobs-jj-e12629-c1-eyeglasses_g_3169-removebg-preview_slke7i.png",
    fastDelivery: true,
    discount: "20",
    rating: 4.9,
    count: 0,
    categoryName: "round",
  },
  {
    _id: uuid(),
    title: "team-secret-Hoodie",
    name: "Team Secret Hoodie",
    price: "10099",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647753693/AegisStore/products/hoodies/TeamSecretHoodie_gif8bx.webp",
    fastDelivery: true,
    discount: "20",
    rating: 2.5,
    count: 20,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "corsair-chair",
    name: "Corsair Chair",
    price: "13999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682197/AegisStore/products/chairs/CorsairChiar_wuevyg.webp",
    fastDelivery: true,
    discount: "20",
    rating: 4.3,
    count: 20,
    categoryName: "chair",
  },
  {
    _id: uuid(),
    title: "JJ E11689",
    name: "Black Full Rim Round Eyeglasses",
    brand: "JOHNJACOBS",
    price: "4000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648151350/House%20Of%20Glass/Products/john-jacobs-jj-e11689-full-rim-round-c1-eyeglasses_g_0566-removebg-preview_1_f33oot.png",
    fastDelivery: true,
    discount: "20",
    rating: 0.0,
    count: 20,
    categoryName: "round",
  },
  {
    _id: uuid(),
    title: "og-hoodie",
    name: "OG Hoodie",
    price: "8999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/OGHoodie_pw9jti.webp",
    fastDelivery: true,
    discount: "8",
    rating: 3.6,
    count: 20,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "fnatic-hoodie",
    name: "Fnatic Hoodie",
    price: "7299",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/FnaticHoodie_xrkiuj.webp",
    fastDelivery: true,
    discount: "40",
    rating: 2.5,
    count: 0,
    categoryName: "hoodie",
  },
  {
    _id: uuid(),
    title: "corsair-keyboard",
    name: "Corsair Keyboard",
    price: "3999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682170/AegisStore/products/keyboards/CorsairKeyboard_w6jgoo.webp",
    fastDelivery: false,
    discount: "5",
    rating: 4.1,
    count: 20,
    categoryName: "keyboard",
  },
  {
    _id: uuid(),
    title: "faze-Hoodie",
    name: "Faze Hoodie",
    price: "6999",
    imageUrl:
      "https://res.cloudinary.com/dut75albw/image/upload/v1647682090/AegisStore/products/hoodies/FazeHoodie_jlfohe.webp",
    fastDelivery: true,
    discount: "5",
    rating: 3.1,
    count: 0,
    categoryName: "hoodie",
  },
];
