import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "JJ E13492",
    name: "Silver Black Full Rim Supreme Steel JJ E13492-C2",
    brand: "JOHNJACOBS",
    price: "4000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648149786/House%20Of%20Glass/Products/Silver-Black-Full-Rim-Round-John-Jacobs-Supreme-Steel-JJ-E13492-C2-Eyeglasses_john-jacobs-jj-e13492-c2-eyeglasses_G_8232_10_02_2022-removebg-preview_vyg30e.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.2,
    count: 0,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "JJ E11473",
    name: "Black Full Rim Round Eyeglasses",
    price: "4000",
    brand: "JOHNJACOBS",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150058/House%20Of%20Glass/Products/john-jacobs-jj-e11473-c1-eyeglasses_john-jacobs-jj-e11473-c1-eyeglasses_john-jacobs-jj-e11473-c1-eyeglasses_g_0143_1-removebg-preview_lifc2w.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 3.9,
    count: 0,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "VC S11748-C4 ",
    name: "Grey Full Rim Round Sunglasses",
    price: "1499",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649348331/House%20Of%20Glass/Products/Sunglasses/Gunmetal-Black-Light-Grey-Full-Rim-Round-Vincent-Chase-Polarized-VINTAGE-VC-S11164-C7-Polarized-Sunglasses_vincent-chase-vc-s11164-c7-full-rim-steel-new-sunglasses_sunglasses_g_5245_118_02_2022-remove_znybyn.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 4.2,
    count: 0,
    categoryName: "SUNGLASSES",
  },
  {
    _id: uuid(),
    title: "VC S14534-C2",
    name: "Brown Full Rim Wayfarer Sunglasses",
    brand: "RAYBAN",
    price: "1499",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649348990/House%20Of%20Glass/Products/Sunglasses/brown-grey-gradient-full-rim-wayfarer-vincent-chase--urban-retro-vc-s14534-c2-polarized-sunglasses_g_9278_01_04_2022-removebg-preview_x3ovi5.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 3.5,
    count: 10,
    categoryName: "SUNGLASSES",
  },
  {
    _id: uuid(),
    title: "S11167-C7",
    name: "Black Full Rim Wayfarer Sunglasses",
    price: "7299",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649348793/House%20Of%20Glass/Products/Sunglasses/Black-Blue-Full-Rim-Wayfarer-Vincent-Chase-Polarized-MIRAGE-VC-S11167-C7-Polarized-Sunglasses_vincent-chase-polarized-vc-s11167-c7-sunglasses_sunglasses_g_1612_1_118_02_2022-removebg-preview_jbemgw.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 4.9,
    count: 4,
    categoryName: "SUNGLASSES",
  },
  {
    _id: uuid(),
    title: "FOS 7108",
    name: "Matte Grey Transparent Full Rim Round Eyeglasses",
    brand: "VINCENTCHASE",
    price: "7400",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150578/House%20Of%20Glass/Products/fossil-fos-7108-63m-eyeglasses_G_6613-removebg-preview_phw0dr.png",
    fastDelivery: true,
    discount: 0.6,
    rating: 4.9,
    count: 20,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "S14597-C1",
    name: "Black Full Rim Round Sunglasses",
    price: "5999",
    brand: "RAYBAN",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649348588/House%20Of%20Glass/Products/Sunglasses/black-green-full-rim-round-vincent-chase-polarized-urban-retro-vc-s14597-c1-sunglasses_g_94364_4_22-removebg-preview_tzni8o.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 4.3,
    count: 50,
    categoryName: "SUNGLASSES",
  },
  {
    _id: uuid(),
    title: " S14505-C5",
    name: "Silver Full Rim Round Sunglasses",
    price: "10999",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649349111/House%20Of%20Glass/Products/Sunglasses/silver-blue-full-rim-round-vincent-chase-livewire-vc-s14505-c5-polarized-sunglasses_g_7703-removebg-preview_k81bpt.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.5,
    count: 31,
    categoryName: "SUNGLASSES",
  },
  {
    _id: uuid(),
    title: " E11824-C3",
    name: "Gold Transparent Full Rim Cat Eye Eyeglasses",
    price: "4499",
    brand: "RAYBAN",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649349318/House%20Of%20Glass/Products/Transparent/Gold-Transparent-Full-Rim-Cat-Eye-Lenskart-Air-Signia-LA-E11824-C3-Eyeglasses_lenskart-air-la-e11824-c3-eyeglasses_G_863407_02_2022-removebg-preview_sx1tnp.png",
    fastDelivery: TrustedTypePolicyFactory,
    discount: 0.625,
    rating: 4.0,
    count: 20,
    categoryName: "TRANSPARENT",
  },
  {
    _id: uuid(),
    title: "E14583",
    name: "Blue Transparent Full Rim Cat Eye Eyeglasses",
    price: "5999",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649349440/House%20Of%20Glass/Products/Transparent/lenskart-air-la-e14585-c3-eyeglasses_g_893523_02_2022-removebg-preview_bnyzb6.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.6,
    count: 11,
    categoryName: "CATEYE",
  },
  {
    _id: uuid(),
    title: "VC E12707",
    name: "Grey Silver Full Rim Round Eyeglasses",
    brand: "VINCENTCHASE",
    price: "999",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648150953/House%20Of%20Glass/Products/vincent-chase-vc-e12707-foll-rim-rnd-tr90ss-mtl-c5-eyegasus_g_9058-removebg-preview_ju7nnc.png",
    fastDelivery: false,
    discount: 0,
    rating: 4.5,
    count: 20,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "S14527-C1",
    name: "Black Full Rim Wayfarer Sunglasses",
    price: "9299",
    brand: "JOHNJACOBS",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649350681/House%20Of%20Glass/Products/Sunglasses/black-blue-full-rim-wayfarer-vincent-chase-polarized-athleisure-vc-s14527-c1-sunglasses_g_8644-removebg-preview_uvmyvs.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 4.1,
    count: 20,
    categoryName: "RETRO",
  },
  {
    _id: uuid(),
    title: "JJ E12629",
    name: "Pro Titanium Silver Rimless Round Eyeglasses",
    brand: "JOHNJACOBS",
    price: "5000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648151070/House%20Of%20Glass/Products/john-jacobs-jj-e12629-c1-eyeglasses_g_3169-removebg-preview_slke7i.png",
    fastDelivery: true,
    discount: "20",
    rating: 4.9,
    count: 0,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: "E11824-C2",
    name: "Gold Tortoise Cat Eye Eyeglasses",
    price: "10099",
    brand: "JOHNJACOBS",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649349716/House%20Of%20Glass/Products/Transparent/lenskart-air-la-e11824-fall-rim-hexagonal-tr90-c1-eyeglasses_lenskart-air-la-e11824-fall-rim-hexagonal-tr90-c1-eyeglasses_G_9054_1-removebg-preview_ihezz5.png",
    fastDelivery: true,
    discount: 0.6,
    rating: 3.5,
    count: 20,
    categoryName: "CATEYE",
  },
  {
    _id: uuid(),
    title: "GRZZ",
    name: "Matte Black Gunmetal Full Rim Rectangle Eyeglasses",
    price: "13999",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649349859/House%20Of%20Glass/Products/Transparent/fos-fos-7078-g-rzz-eyeglasses_G_6910-removebg-preview_oqtnxx.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.3,
    count: 20,
    categoryName: "CATEYE",
  },
  {
    _id: uuid(),
    title: "JJ E11689",
    name: "Black Full Rim Round Eyeglasses",
    brand: "JOHNJACOBS",
    price: "4000",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1648151350/House%20Of%20Glass/Products/john-jacobs-jj-e11689-full-rim-round-c1-eyeglasses_g_0566-removebg-preview_1_f33oot.png",
    fastDelivery: true,
    discount: "20",
    rating: 0.0,
    count: 20,
    categoryName: "ROUND",
  },
  {
    _id: uuid(),
    title: " E13919-C2",
    name: "Black Grey Transparent Full Rim Aviator Eyeglasses",
    price: "8999",
    brand: "RAYBAN",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649350086/House%20Of%20Glass/Products/RETRO/vincent-chase-vc-e13920-c2-eyeglasses_g_4838-removebg-preview_wq8tul.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 3.6,
    count: 20,
    categoryName: "RETRO",
  },
  {
    _id: uuid(),
    title: "E14236-C1",
    name: "Black Transparent Full Rim Aviator Eyeglasses",
    price: "7299",
    brand: "VINCENTCHASE",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649350314/House%20Of%20Glass/Products/RETRO/vincent-chase-vc-e14236-c1-eyeglasses_G_5785-removebg-preview_b446xu.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 4.5,
    count: 0,
    categoryName: "RETRO",
  },
  {
    _id: uuid(),
    title: "E11288-E",
    name: "Matte Blue Gunmetal Full Rim Aviator Eyeglasses",
    price: "3999",
    brand: "RAYBAN",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649350459/House%20Of%20Glass/Products/RETRO/lenskart-air-la-e11288-c4-c4-eyeglasses_G_4982-removebg-preview_ocpbeu.png",
    fastDelivery: false,
    discount: 0.625,
    rating: 4.1,
    count: 20,
    categoryName: "RETRO",
  },
  {
    _id: uuid(),
    title: "E14725-C1",
    name: "Blue Tortoise Full Rim Aviator Eyeglasses",
    price: "6999",
    brand: "RAYBAN",
    imageUrl:
      "https://res.cloudinary.com/dkqrmlxlg/image/upload/v1649350531/House%20Of%20Glass/Products/RETRO/blue-tortoise-full-rim-aviator-vicent-chase-classic-acetate-vc-e14725-c1-eyeglasses_g_8864_24_03_2022-removebg-preview_t7fhra.png",
    fastDelivery: true,
    discount: 0.625,
    rating: 3.1,
    count: 0,
    categoryName: "TRANSPARENT",
  },
];
